### ISSUE TITLE
error。

### ISSUE THREAD

**Issue by z6101681** [pathetiq/BurpSmartBuster#16]
![default](https://cloud.githubusercontent.com/assets/15312660/23595492/394b236a-025d-11e7-8d63-50d05736ff8e.png)

**Comment by z6101681** [comment]
Windows environment can't  installed properly

**Comment by pathetiq** [comment]
Have you try to install using the Burp Store inside the Extender Tab inside Burp Suite? It should work. 

Manual installation wasn't tested on windows like explained on the Wiki page. But the error here maybe make sure the requirements.txt doesn't have any space or special characters that might be copied by error.

**Comment by pathetiq** [comment]
No update, but should be fixed using burp store (in extender tab) inside Burp Suite.
