### ISSUE TITLE
Download from burp app store,but load the plugins error

### ISSUE THREAD

**Issue by z6101681** [pathetiq/BurpSmartBuster#17]
![default](https://cloud.githubusercontent.com/assets/15312660/24131539/30057566-0e2a-11e7-8c0d-af8cef459a65.png)

**Comment by pathetiq** [comment]
Hi,

Please output the error to a file and paste the whole error here. Also list if you have:
- Install from burp store?
- Configure Jython.jar (version 2.7) path in the option tab?
- Which version of Burp you have
- Which OS?

Thanks

**Comment by z6101681** [comment]
I Install this plugin from burp BApp store.
Mine burp version is Pro v1.7.17
I'm pretty sure I installed jython 2. 7 successful
Mine work OS is win 7 x64
 
This is the error messages.
[burperrorlog.txt](https://github.com/pathetiq/BurpSmartBuster/files/857112/burperrorlog.txt)

**Comment by z6101681** [comment]
![default](https://cloud.githubusercontent.com/assets/15312660/24132781/ee1812b8-0e32-11e7-8c75-f4156de4b511.png)
Another python plugin is normal。

**Comment by z6101681** [comment]
[burperrorlog.txt](https://github.com/pathetiq/BurpSmartBuster/files/857125/burperrorlog.txt)

**Comment by 500646** [comment]
i have the same issue. jython 2.7, install from the BApp store

**Comment by pathetiq** [comment]
Hi can you give the full error log too? 

Still can't reproduce this bug, it seems to be link to a Java library in Jython on Windows that I don't control.

**Comment by SecureThisShit** [comment]
I think there are Missing Module Dependencies in the Python 2.7 Standalone Jar on Windows.

[Error.txt](https://github.com/pathetiq/BurpSmartBuster/files/1378783/Error.txt)

**Comment by pathetiq** [comment]
I recently had a similar error on windows.

Try downloading Jython 2.7.1 which is suppose to fix it: https://repo1.maven.org/maven2/org/python/jython-installer/2.7.1/jython-installer-2.7.1.jar

**Comment by SecureThisShit** [comment]
That didnt work for me. Same Error. And i cannot find a module named exceptions.

**Comment by SecureThisShit** [comment]
Issue solved for me, #23

**Comment by tarrenj** [comment]
Getting same error on Windows 10 with BurpSuitePro.  Tested with jython 2.7.0 and 2.7.1, with both the standalone JAR and the JAR created when installing full jython.  Resolved with `...\jython2.7.1\bin\pip.exe install bs4 nltk TextBlob requests tlk`

Getting another issue now.
