### ISSUE TITLE
n00b question

### ISSUE THREAD

**Issue by securisec** [pathetiq/BurpSmartBuster#20]
I am not how to actually use the extension. Current setup is on a mac, jython installed, install burpsmartbuster from bapp store, and added targers to scope. refreshed the page, but no cigar ... now what?

Thanks!

**Comment by pathetiq** [comment]
Hi,
In the extender tab, you will see the output of the plugin. I suggest that you choose output to file to make sure you don't lose data.

Let me know if there's anything else.

**Comment by securisec** [comment]
Thanks! It now works... I will play around with it a bit to see if i can add http verb detection to it.

**Comment by pathetiq** [comment]
Awesome, please submit your pull request for the verb detection seems like a good addition and should not be to hard. Thanks again.
