### ISSUE TITLE
Fails to load when downloaded from BApp Store on Windows 10

### ISSUE THREAD

**Issue by tarrenj** [pathetiq/BurpSmartBuster#25]
Using BurpSuitePro on Windows 10, installed BurpSmartBuster from BApp Store.
Got errors using jython2.7.0 standalone, switched to jython2.7.1 full install after reading issue https://github.com/pathetiq/BurpSmartBuster/issues/17, also ran `...\jython2.7.1\bin\pip.exe install ps4 nltk TextBlob requests tld` which resolved several other issues.

Still unable to load BurpSmartBuster, and the error log is now cutting off the top of the error so I can't see what's wrong:
[BurpSmartBusterError.txt](https://github.com/pathetiq/BurpSmartBuster/files/1518285/BurpSmartBusterError.txt)

Versions installed:
[pipVersions.txt](https://github.com/pathetiq/BurpSmartBuster/files/1518310/pipVersions.txt)

**Comment by tarrenj** [comment]
There are some mismatches between the versions I've got installed and the versions in the Wiki:

Requests: 2.18.4 installed, 2.10 in Wiki
nltk:          3.2.5 installed,   3.1 in Wiki
TextBlob:  0.14.0 installed,  0.11.0 in Wiki

The requirements for TextBlob and nltk are because jython2.7.0 doesn't support Sqlite3.  This is [roadmaped](http://bugs.jython.org/issue1682864) for jython2.7.2.

Trying to roll back those two packages now...

**Comment by tarrenj** [comment]
Resolved with:
`...\jython2.7.1\bin\pip.exe uninstall TextBlob nltk`
`...\jython2.7.1\bin\pip.exe install TextBlob==0.11.0 nltk==3.1`

Closing issue. @pathetiq if you want any more info or something just let me know.

**Comment by pathetiq** [comment]
Technically the requirements.txt should make all this happen already. I don't know why your packages got mixed up for no reason. 

See https://github.com/pathetiq/BurpSmartBuster/blob/master/requirements.txt

**Comment by tarrenj** [comment]
It probably would have worked had I built it myself, but I was hoping to just download the stable jython standalone and install the app from the BApp Store.  Does Burp follow the versions specified in that .txt file when a user installs from the BApp Store?

**Comment by pathetiq** [comment]
It is suppose too, they created that file actually. Will check with them when I got a minute.
